# Generated by Django 2.1.4 on 2019-04-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipingAddress1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingCity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingCountry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingPostCode',
        ),
    ]
